CREATE TABLE CSE532.COLLISION_ALL(DATE DATE, TIME TIME, ZIPCODE VARCHAR(6), LATITUDE DECIMAL(9,6), LONGITUDE DECIMAL(9,6), 
CONTRIBUTING_FACTOR_VEHICLE_1 VARCHAR(100), CONTRIBUTING_FACTOR_VEHICLE_2 VARCHAR(100), 
UNIQUE_KEY VARCHAR(10) NOT NULL PRIMARY KEY, VEHICLE_TYPE_CODE_1 VARCHAR(100), VEHICLE_TYPE_CODE_2 VARCHAR(100));

CREATE INDEX IDX_DATE ON CSE532.COLLISION_ALL (DATE);
CREATE INDEX IDX_TIME ON CSE532.COLLISION_ALL (TIME);
CREATE INDEX IDX_ZIPCODE ON CSE532.COLLISION_ALL (ZIPCODE);
CREATE INDEX IDX_LATITUDE ON CSE532.COLLISION_ALL (LATITUDE);
CREATE INDEX IDX_LONGITUDE ON CSE532.COLLISION_ALL (LONGITUDE);


