WITH HOURLY_MONTHLY AS (
	SELECT EXTRACT(HOUR FROM TIME) AS PHOUR, EXTRACT(MONTH FROM DATE) AS PMONTH, EXTRACT(YEAR FROM DATE) AS PYEAR, COUNT(*) AS COLLISION_COUNT FROM CSE532.COLLISION_ALL c 
	WHERE c.TIME IS NOT NULL AND c.DATE IS NOT NULL GROUP BY CUBE (c.TIME, c.DATE)
)
SELECT HOUR, SUM(COLLISION_COUNT) AS COLLISION_COUNT FROM (
SELECT PHOUR AS HOUR, PMONTH AS MONTH, PYEAR AS YEAR, SUM(COLLISION_COUNT) AS COLLISION_COUNT FROM HOURLY_MONTHLY WHERE PHOUR IS NOT NULL AND PMONTH IS NOT NULL AND PYEAR IS NOT NULL GROUP BY PYEAR, PMONTH, PHOUR ORDER BY COLLISION_COUNT DESC
)GROUP BY HOUR ORDER BY COLLISION_COUNT DESC LIMIT 1;