CREATE TABLE CSE532.COLLISION(DATE DATE, TIME TIME, ZIPCODE VARCHAR(6), LATITUDE DECIMAL(9,6), LONGITUDE DECIMAL(9,6), 
CONTRIBUTING_FACTOR_VEHICLE_1 VARCHAR(100), CONTRIBUTING_FACTOR_VEHICLE_2 VARCHAR(100), 
UNIQUE_KEY VARCHAR(10) NOT NULL PRIMARY KEY, VEHICLE_TYPE_CODE_1 VARCHAR(100), VEHICLE_TYPE_CODE_2 VARCHAR(100));