WITH POPULATION_RANK(P_ZIPCODE, POPULATION_RANK) AS (SELECT ZIPCODE, RANK() OVER ( ORDER BY POPULATION DESC) POPULATION_RANK FROM CSE532.ZIPCENSUS z LIMIT 10),
COLLISION_RANK(C_ZIPCODE, COLLISIONS, COLLISION_RANK) AS (SELECT  ZIPCODE, COUNT(ZIPCODE), RANK() OVER (ORDER BY COUNT(ZIPCODE) DESC) COLLISION_RANK FROM CSE532.COLLISION c GROUP BY ZIPCODE LIMIT 10)
SELECT * FROM POPULATION_RANK INNER JOIN COLLISION_RANK ON POPULATION_RANK.P_ZIPCODE=COLLISION_RANK.C_ZIPCODE;

