DROP INDEX CSE532.FACILITYIDX;
DROP INDEX CSE532.ZIPIDX;
DROP INDEX CSE532.ATTRVLE;
DROP INDEX CSE532.ZIPCODEIDX;
DROP INDEX CSE532.ZIPCODEIDX2;
DROP INDEX idx_facility_certification_id_value;

CREATE INDEX CSE532.FACILITYIDX ON CSE532.FACILITY(GEOLOCATION) EXTEND USING DB2GSE.SPATIAL_INDEX(0.85, 2, 5);

CREATE INDEX CSE532.ZIPIDX ON CSE532.USZIP(SHAPE) EXTEND USING DB2GSE.SPATIAL_INDEX(0.85, 2, 5);

CREATE INDEX CSE532.ATTRVLE ON CSE532.FACILITYCERTIFICATION(AttributeValue);

CREATE INDEX CSE532.ZIPCODEIDX ON CSE532.FACILITY(ZIPCODE);

CREATE INDEX CSE532.ZIPCODEIDX2 ON CSE532.USZIP(ZCTA5CE10);

CREATE INDEX CSE532.idx_facility_certification_id_value ON cse532.facilitycertification(FacilityID, AttributeValue);

RUNSTATS ON TABLE CSE532.FACILITY AND INDEXES ALL;

RUNSTATS ON TABLE CSE532.USZIP AND INDEXES ALL;
