DROP TABLE IF EXISTS CSE532.FACILITYCERTIFICATION;

CREATE TABLE CSE532.FACILITYCERTIFICATION(
FacilityID VARCHAR(16),
FacilityName VARCHAR(128),
Description VARCHAR(128),
AttributeType VARCHAR(128),
AttributeValue VARCHAR(128),
MeasureValue SMALLINT,
County VARCHAR(16)
);
