INSERT INTO CSE532.FACILITY(FACILITYID, FACILITYNAME, DESCRIPTION, ADDRESS1, ADDRESS2, CITY, STATE, ZIPCODE, COUNTYCODE, COUNTY, GEOLOCATION)
SELECT
   FACILITYID, FACILITYNAME, DESCRIPTION, ADDRESS1, ADDRESS2, CITY, STATE, ZIPCODE, COUNTYCODE, COUNTY, DB2GSE.ST_POINT(LONGITUDE, LATITUDE, 1) as GEOLOCATION
FROM CSE532.FACILITYORIGINAL;