SELECT CURRENT TIMESTAMP FROM SYSIBM.SYSDUMMY1;


SELECT
    CERT.FACILITYID, CERT.FACILITYNAME, CERT.COUNTY, DB2GSE.ST_ASTEXT(FACI.GEOLOCATION) AS POINT,
    DB2GSE.ST_DISTANCE( FACI.GEOLOCATION, DB2GSE.ST_POINT(-73.016479, 40.891720, 1), 'KILOMETER') AS Distance
FROM CSE532.FACILITYCERTIFICATION CERT JOIN CSE532.FACILITY FACI ON FACI.FACILITYID = CERT.FACILITYID WHERE CERT.ATTRIBUTEVALUE = 'Intensive Care' AND 
DB2GSE.ST_CONTAINS(DB2GSE.ST_BUFFER(DB2GSE.ST_POINT(-73.016479, 40.891720, 1), 100, 'KILOMETER'), FACI.GEOLOCATION) ORDER BY Distance LIMIT 1;

SELECT CURRENT TIMESTAMP FROM SYSIBM.SYSDUMMY1;

