SELECT CURRENT TIMESTAMP FROM SYSIBM.SYSDUMMY1;

WITH ed_zip AS (
  SELECT DISTINCT f.ZIPCODE
  FROM cse532.facilitycertification fc JOIN CSE532.FACILITY f ON f.FACILITYID = fc.FACILITYID
  WHERE fc.AttributeValue = 'Emergency Department'
), ed_zip_shape AS (
  SELECT u1.ZCTA5CE10, u1.SHAPE 
  FROM cse532.uszip u1
  --JOIN cse532.uszip u2 ON DB2GSE.ST_Intersects(u1.SHAPE , u2.SHAPE)
  JOIN ed_zip ON u1.ZCTA5CE10 = ed_zip.ZIPCODE
), zipcode_scope AS(
  SELECT u2.ZCTA5CE10 AS TOTAL_ZIPS FROM CSE532.USZIP u2 INNER JOIN CSE532.FACILITY f2 ON u2.ZCTA5CE10 = f2.FACILITYID WHERE f2.FACILITYID  
), us_zip_zipcode_scope as(
SELECT * FROM CSE532.USZIP u3 join zipcode_scope z ON u3.ZCTA5CE10 = z.TOTAL_ZIPS
), neig_zip AS (
SELECT U.ZCTA5CE10 FROM us_zip_zipcode_scope u,ed_zip_shape
WHERE  U.ZCTA5CE10 <> ed_zip_shape.ZCTA5CE10 AND DB2GSE.ST_INTERSECTS(U.SHAPE, ed_zip_shape.SHAPE)
)
SELECT zz.ZIPCODE  FROM CSE532.FACILITY zz WHERE 
zz.ZIPCODE  NOT IN 
(SELECT * FROM ed_zip) UNION (SELECT * FROM neig_zip);

SELECT CURRENT TIMESTAMP FROM SYSIBM.SYSDUMMY1;
